In [1]:
# Tensorの演算子
# https://qiita.com/hiroyuki827/items/72152cdbcb073f0d4bb7

# インポート
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Model
import tensorflow.keras.layers as layers
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Input
import numpy as np

In [42]:
# 定数配列 : https://www.tensorflow.org/api_docs/python/tf/constant
# Creates a constant tensor from a tensor-like object.
# tf.constant(
#     value, dtype=None, shape=None, name='Const'
# )
a = tf.constant([1,2,3,4])
print(a)
b = tf.constant([1,2,3,4],shape=[2,2])
print(b)

b = tf.add(b,b)
print(b)

# 変数
# tf.Variable(
#     initial_value=None, trainable=None, validate_shape=True, caching_device=None,
#     name=None, variable_def=None, dtype=None, import_scope=None, constraint=None,
#     synchronization=tf.VariableSynchronization.AUTO,
#     aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None
# )
v = tf.Variable([1,2,3,4])
print("v")
print(v)
# 変数と定数の違いは何？？？


# 各種行列
# Ones
c = tf.ones([3,3])
print(c)

# Zeros
d = tf.zeros([3,3])
print(d)

# 乱数配列
initialiser = tf.random_uniform_initializer(minval=-1., maxval=1.)
e = tf.constant(initialiser(shape=[2,2], dtype=tf.float32))
print(e)

# 転置配列
M = tf.constant([6,3,2,4], shape=[2,2])
print(M)
M=tf.transpose(M)
print(M)



tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)
v
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.64552546 -0.41597605]
 [-0.85680056  0.6780026 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[6 3]
 [2 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[6 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [58]:
# 四則演算 : https://qiita.com/hiroyuki827/items/72152cdbcb073f0d4bb7
# 要素ごとの演算になる．
x = tf.constant([6,3])
y = tf.constant([2,3])

# 足し算
out = tf.add(x, y)
print(out)

# 引き算
out = tf.subtract(x, y)
print(out)

# 割り算
out = tf.divide(x, y)
print(out)

# 行列積
M = tf.constant([6,3,2,4], shape=[2,2])
N = tf.constant([1,0,0,1], shape=[2,2])
print(tf.matmul(M,N))

# ベクトル積
v = tf.Variable([[1,2,3]])
w = tf.Variable([[1,2,3]])
print(tf.matmul(v,w,transpose_b=True))






tf.Tensor([8 6], shape=(2,), dtype=int32)
tf.Tensor([4 0], shape=(2,), dtype=int32)
tf.Tensor([3. 1.], shape=(2,), dtype=float64)
tf.Tensor(
[[6 3]
 [2 4]], shape=(2, 2), dtype=int32)
tf.Tensor([[14]], shape=(1, 1), dtype=int32)


In [12]:
# tf.expand_dims : https://www.tensorflow.org/api_docs/python/tf/expand_dims
# tf.expand_dims(
#     input, axis, name=None
# )
image = tf.zeros([10,10,3])
print(image.shape)
image = tf.expand_dims(image, axis=0)
print(image.shape)



(10, 10, 3)
(1, 10, 10, 3)


In [57]:
!tensorboard --logdir ./logs

Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.3.0 at http://localhost:6006/ (Press CTRL+C to quit)
^C
